language: rust
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - rust: nightly
      script:
        - cargo test
    - rust: beta
      script:
        - cargo test
    - rust: stable
      install:
        - rustup component add rustfmt --toolchain stable-x86_64-unknown-linux-gnu
      script:
        - cargo fmt -- --check
        - cargo test

notifications:
  email:
    on_success: never
